//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinyURL.DataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogMessage
    {
        public int Id { get; set; }
        public string Application { get; set; }
        public string Summary { get; set; }
        public string Exception { get; set; }
        public string IP { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    }
}
